language: ruby
cache: bundler
sudo: required
dist: trusty
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - curl -L https://packagecloud.io/michaelmior/coinor/gpgkey | sudo apt-key add -
  - echo "deb https://packagecloud.io/michaelmior/coinor/ubuntu/ precise main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install -y graphviz
  - sudo apt-get install -y coinor-libcbc-dev coinor-libcbc3 coinor-libcoinutils-dev coinor-libcoinutils3v5 coinor-libosi-dev coinor-libosi1 coinor-libclp-dev coinor-libclp1 coinor-libcgl-dev coinor-libcgl1 libstdc++6
  - gem install bundler
rvm:
  - 2.7.1
  - 2.6.6
  # Temporarily disabled until we get this working since it slows down tests
  # - jruby-9.0.5.0
matrix:
  allow_failures:
    - rvm: jruby-9.0.5.0
script:
  - sed -i '/^--tag/d' .rspec
  - bundle exec rspec
